version: '3.0'

services:
  mariadb:
    image: mariadb:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./create-databases.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - 3306:3306

  informatics:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.test

    env_file:
      - test.env
    depends_on:
      - mariadb

#    command: 'sh -c "sleep 10 && flask test --teamcity"'