openapi: 3.0.0

info:
  title: Informatics auth
  version: 1.0.0
  description: Informatics auth API

servers:
  - url: http://85.93.88.189:12347
    description: Dev-сервер

tags:
  - name: Auth
    description: Авторизация

paths:
  /auth/signin/:
    post:
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Username
                password:
                  type: string
                  description: Пароль

      summary: Залогиниться (получить токены)
      responses:
        200:
          description: Пользователь
          content:
            application/json:
              schema:
                $ref: '../models.yaml#/components/schemas/UserAuthSchema'
        404:
          description: Пользовалель не найден
          allOf:
            - $ref: '../error_responses.yaml#/components/responses/NotFound'

        401:
          description: Неправильный пароль
          allOf:
            - $ref: '../error_responses.yaml#/components/responses/Forbidden'

  /auth/signout/:
    post:
      tags:
        - Auth

      summary: Разлогиниться

      security:
        - jwt-token-auth: []

      responses:
        200:
          description: Токены удалены

  /auth/refresh/:
    post:
      tags:
        - Auth

      summary: Получить новый token

      security:
        - jwt-token-auth: []

      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
                  description: Refresh Token

      responses:
        200:
          description: Пользователь
          content:
            application/json:
              schema:
                $ref: '../models.yaml#/components/schemas/UserAuthSchema'
        403:
          description: Рефреш токен протух
          allOf:
            - $ref: '../error_responses.yaml#/components/responses/BadRequest'

components:
  securitySchemes:
    jwt-token-auth:
      type: apiKey
      in: header
      name: Authorization
