openapi: 3.0.0

info:
  title: Informatics auth
  version: 1.0.0
  description: Informatics auth API

servers:
  - url: http://localhost
    description: Dev-сервер

tags:
  - name: Auth
    description: Авторизация

paths:
  /auth/signin/:
    post:
      tags:
        - Auth

      summary: Залогиниться (получить токены)
      responses:
        200:
          description: Пользователь
          content:
            application/json:
              schema:
                $ref: '../models.yaml#/components/schemas/UserAuthSchema'
        404:
          description: Пользовалель не найден
          allOf:
            - $ref: '../error_responses.yaml#/components/responses/NotFound'

        401:
          description: Неправильный пароль
          allOf:
            - $ref: '../error_responses.yaml#/components/responses/Forbidden'

  /auth/signout/:
    post:
      tags:
        - Auth

      summary: Разлогиниться

      security:
        - jwt-token-auth: []

      responses:
        200:
          description: Токены удалены

  /auth/refresh/:
    post:
      tags:
        - Auth

      summary: Получить новый token

      security:
        - jwt-token-auth: []

      requestBody:
        type: object
        properties:
          refresh_token:
            type: string
            description: Refresh Token

      responses:
        200:
          description: Пользователь
          content:
            application/json:
              schema:
                $ref: '../models.yaml#/components/schemas/UserAuthSchema'
        403:
          description: Рефреш токен протух
          allOf:
            - $ref: '../error_responses.yaml#/components/responses/BadRequest'
