openapi: 3.0.0

info:
  title: Informatics contest
  version: 1.0.0
  description: Informatics contest

servers:
  - url: http://85.93.88.189:12347
    description: Dev-сервер

tags:
  - name: Contest
    description: Контест
  - name: Submissions
    descriprion: Посылки


paths:
  /contest/{contest_id}:
    get:
      tags:
        - Contest

      summary: Контест с задачами по chapterid из moodle

      parameters:
        - in: path
          name: contest_id
          schema:
            type: integer
          required: true
          description: Numeric ID of the contest to get

      security:
        - jwt-token-auth: []

      responses:
        200:
          description: Контест с задачами
          content:
            application/json:
              schema:
                $ref: '../models.yaml#/components/schemas/ContestSchema'
        404:
          description: Контест не найден
          allOf:
            - $ref: '../error_responses.yaml#/components/responses/NotFound'

  /contest/problem/{problem_id}:
    get:
      tags:
        - Contest

      summary: Задача

      parameters:
        - in: path
          name: problem_id
          schema:
            type: integer
          required: true
          description: Numeric ID of the problem to get

      security:
        - jwt-token-auth: []

      responses:
        200:
          description: Задача
          content:
            application/json:
              schema:
                $ref: '../models.yaml#/components/schemas/ProblemSchema'
        404:
          description: Задача не найдена
          allOf:
            - $ref: '../error_responses.yaml#/components/responses/NotFound'

  /contest/problem/{problem_id}/submission:
    get:
      tags:
        - Submissions

      summary: Фильтр по посылкам

      security:
        - jwt-token-auth: []

      parameters:
        - in: path
          name: problem_id
          schema:
            type: integer
          required: true
          description: Numeric ID of the problem to get
        - in: path
          name: group_id
          schema:
            type: integer
            description: Группа
        - in: path
          name: lang_id
          schema:
            type: integer
            description: Язык
        - in: path
          name: status_id
          schema:
            type: integer
            description: Статус посылки
        - in: path
          name: statement_id
          schema:
            type: integer
            description: Id контеста
        - in: path
          name: count
          schema:
            type: integer
            description: Количество на странице (не более 100)
        - in: path
          name: page
          schema:
            type: integer
            description: Номер страницы
            default: 1
        - in: path
          name: from_timestamp
          schema:
            type: integer
            description: С какого времени (-1 если фильтровать не нужно)
        - in: path
          name: to_timestamp
          schema:
            type: integer
            description: По какое время (-1 если фильтровать не нужно)

      responses:
        200:
          description: Отфильтрованные посылки
          content:
            application/json:
              schema:
                $ref: '../models.yaml#/components/schemas/ProblemSubmissionSchema'
    post:
      tags:
        - Submissions

      summary: Отправить посылку

      security:
        - jwt-token-auth: []

      requestBody:
        content:
          multipart/json:
            shema:
              type: object
              properties:
                lang_id:
                  type: integer
                  description: Язык
                statement_id:
                  type: integer
                  description: id контеста
                file:
                  type: string
                  format: binary

      responses:
        200:
          description: Посылка отправлена

        404:
          description: Задача не найдена
          allOf:
            - $ref: '../error_responses.yaml#/components/responses/NotFound'

        400:
          description: Пустой файл или дубликат посылки или файл слишком большой
          allOf:
            - $ref: '../error_responses.yaml#/components/responses/BadRequest'

  /contest/run/{run_id}/source:
    get:
      summary: Получить исходник посылки
      parameters:
        - in: path
          name: run_id
          schema:
            type: integer
          required: true
          description: Numeric ID of the run to get source

      security:
       - jwt-token-auth: []

      responses:
        200:
          description: Исходник посылки
          content:
            application/json:
              schema:
                type: object
                properties:
                  language_id:
                    type: integer
                    description: Язык программирования посылкии
                  source:
                    type: string
                    descroption: Исходник посылки
        404:
          description: Посылка не найдена
          allOf:
            - $ref: '../error_responses.yaml#/components/responses/NotFound'

  /contest/run/{run_id}/protocol:
    get:
      summary: Получить протокол тестирования посылки
      parameters:
        - in: path
          name: run_id
          schema:
            type: integer
          required: true
          description: Numeric ID of the run to get source

      security:
       - jwt-token-auth: []

      responses:
        200:
          description: Протокол тестирования посылки
          content:
            application/json:
              schema:
                $ref: '../error_responses.yaml#/components/responses/RunProtocolSchema'
        404:
          description: Посылка не найдена
          allOf:
            - $ref: '../error_responses.yaml#/components/responses/NotFound'


