openapi: 3.0.0

info:
  title: Informatics workshop
  version: 1.0.0
  description: Informatics workshop

servers:
  - url: http://rmatics.tcsbank.info:12347
    description: Dev-сервер

tags:
  - name: Workshop
    descriprion: Сборы


paths:
  /workshop/{workshop_id}:
    get:
      tags:
        - Workshop

      summary: Воркшоп (сбор) со списком контестов, взодяшим в него. Каждый контекст имеет в себе statement, который его описывает.

      parameters:
        - in: path
          name: workshop_id
          schema:
            type: integer
          required: true
          description: Numeric ID of the workshop to get

      security:
        - jwt-token-auth: []

      responses:
        200:
          description: Воркшоп со списком контестов. Контест содержит описание, но не включает список своих проблем.
          content:
            application/json:
              schema:
                $ref: '../models.yaml#/components/schemas/WorkshopSchema'
        404:
          description: Воркошп не найден или у пользователя нет приглашения в него
          allOf:
            - $ref: '../error_responses.yaml#/components/responses/NotFound'

  /workshop/{workshop_id}/monitor:
    get:
      tags:
        - Workshop

      summary: Результаты сборов

      parameters:
        - in: path
          name: workshop_id
          schema:
            type: integer
          required: true
          description: Numeric ID of the workshop to get

      security:
        - jwt-token-auth: []

      responses:
        200:
          description: Результаты сборов, с пользователями и задачами, входящими в него
          content:
            application/json:
              schema:
                $ref: '../models.yaml#/components/schemas/MonitorSchema'
        404:
          description: Результат не найден или у пользователя нет приглашения в него
          allOf:
            - $ref: '../error_responses.yaml#/components/responses/NotFound'

  /workshop/{workshop_id}/join:
    post:
      tags:
        - Workshop

      summary: Записаться на сбор 

      parameters:
        - in: path
          name: workshop_id
          schema:
            type: integer
          required: true
          description: Numeric ID of the workshop to join at
        - in: query
          name: token
          schema:
            type: string
          required: true
          description: Токен безопасности для записи на сбор 

      responses:
        200:
          description: Приглашние на сбор со статусом 
          content:
            application/json:
              schema:
                $ref: '../models.yaml#/components/schemas/WorkshopConnectionSchema'
        404:
          description: Возвращается, если или не найден Сбор по предоставленному Workshop_id или предоставен неверный token

